apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abhijit06021997/argocd-apps
    targetRevision: HEAD
    path: /
  destination:
    server: https://kubernetes.default.svc
    namespace: mysite
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
